# gtp 10k datastore

python master_script.py --log-folder logs/gpt_10k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/gpt_10k/preprocessed --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/gpt_10k/index_only --num-for-training 10000 --code-size 64 --ncentroids 4096 --train-index dstores/gpt_10k/index_only.4096.index.trained --save-job --merge-dstore-job --train-index-job

python master_script.py --log-folder logs/gpt_10k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/gpt_10k/preprocessed --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/gpt_10k/index_only --num-for-training 10000 --code-size 64 --ncentroids 4096 --train-index dstores/gpt_10k/index_only.4096.index.trained  --faiss-index dstores/gpt_10k/index_only.4096.index --write-merged-index dstores/gpt_10k/index_only.4096.index --corpus-identifiers vw --add-keys-job --merge-index-job

python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --max-tokens 4096 --gen-subset test --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu --knnmt --k 64 --probe 32 --indexfile dstores/gpt_10k/index_only.4096.index --model-overrides "{'knn_keytype': 'last_ffn_input'}" --knn-keytype last_ffn_input --knn-embed-dim 512 --no-load-keys  --knn-temp 10 --knn-sim-func do_not_recomp_l2 --lmbda 0.8 --use-faiss-only

python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --gen-subset test --max-tokens 4096 --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu
