
# 10k data store
python master_script.py --log-folder logs/vw_10k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_10k/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_10k/index_only --num-for-training 10000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_10k/index_only.4096.index.trained --save-job --merge-dstore-job --train-index-job


python master_script.py --log-folder logs/vw_10k/build_index/add_merge_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_10k/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_10k/index_only --num-for-training 10000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_10k/index_only.4096.index.trained  --faiss-index dstores/vw_10k/index_only.4096.index --write-merged-index dstores/vw_10k/index_only.4096.index --corpus-identifiers vw --add-keys-job --merge-index-job
# python master_script.py --log-folder logs/vw_10k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_10k/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_10k/index_only --num-for-training 10000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_10k/index_only.4096.index.trained --save-job --merge-dstore-job --train-index-job



python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --max-tokens 4096 --gen-subset test --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu --knnmt --k 64 --probe 32 --indexfile dstores/vw_1m/index_only.4096.index --model-overrides "{'knn_keytype': 'last_ffn_input'}" --knn-keytype last_ffn_input --knn-embed-dim 512 --no-load-keys  --knn-temp 10 --knn-sim-func do_not_recomp_l2 --lmbda 0.8 --use-faiss-only


python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --gen-subset test --max-tokens 4096 --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu  

# 100k data store
python master_script.py --log-folder logs/vw_100k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_100k/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_100k/index_only --num-for-training 100000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_100k/index_only.4096.index.trained --save-job --merge-dstore-job --train-index-job


python master_script.py --log-folder logs/vw_100k/build_index/add_merge_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_100k/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_100k/index_only --num-for-training 100000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_100k/index_only.4096.index.trained  --faiss-index dstores/vw_100k/index_only.4096.index --write-merged-index dstores/vw_100k/index_only.4096.index --corpus-identifiers vw --add-keys-job --merge-index-job

python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --max-tokens 4096 --gen-subset test --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu --knnmt --k 64 --probe 32 --indexfile dstores/vw_100k/index_only.4096.index --model-overrides "{'knn_keytype': 'last_ffn_input'}" --knn-keytype last_ffn_input --knn-embed-dim 512 --no-load-keys  --knn-temp 10 --knn-sim-func do_not_recomp_l2 --lmbda 0.8 --use-faiss-only

# 100k from 1 million
python master_script.py --log-folder logs/vw_100k_from_1m/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_100k/index_only --num-for-training 100000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_100k_from_1m/index_only.4096.index.trained --save-job --merge-dstore-job --train-index-job


python master_script.py --log-folder logs/vw_100k_from_1m/build_index/add_merge_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/vw_100k_from_1m/index_only --num-for-training 100000 --code-size 64 --ncentroids 4096 --train-index dstores/vw_100k_from_1m/index_only.4096.index.trained  --faiss-index dstores/vw_100k_from_1m/index_only.4096.index --write-merged-index dstores/vw_100k_from_1m/index_only.4096.index --corpus-identifiers vw --add-keys-job --merge-index-job

python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --max-tokens 4096 --gen-subset test --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu --knnmt --k 64 --probe 32 --indexfile dstores/vw_100k_from_1m/index_only.4096.index --model-overrides "{'knn_keytype': 'last_ffn_input'}" --knn-keytype last_ffn_input --knn-embed-dim 512 --no-load-keys  --knn-temp 10 --knn-sim-func do_not_recomp_l2 --lmbda 0.8 --use-faiss-only

# medical 248k dstores

python master_script.py --log-folder logs/medical_100k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/medical/medical/preprocessed --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/medical_100k/index_only --num-for-training 248099 --code-size 64 --ncentroids 4096 --train-index dstores/medical_100k/index_only.4096.index.trained --save-job --merge-dstore-job --train-index-job

python master_script.py --log-folder logs/medical_100k/build_index --slurm-name vw --bytes-per-token 2 --model /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --bpecodes /home/ababouelenin/CustomTranslation/knnmt/blob_data/vocab/deen_spm/sentencepiece.bpe.vocab --save-data /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/medical/medical/preprocessed --binfile train.de-en.en.bin --num-shards 1 --dstore-mmap dstores/medical_100k/index_only --num-for-training 248099 --code-size 64 --ncentroids 4096 --train-index dstores/medical_100k/index_only.4096.index.trained  --faiss-index dstores/medical_100k/index_only.4096.index --write-merged-index dstores/medical_100k/index_only.4096.index --corpus-identifiers vw --add-keys-job --merge-index-job

python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --max-tokens 4096 --gen-subset test --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu --knnmt --k 64 --probe 32 --indexfile dstores/medical_100k/index_only.4096.index --model-overrides "{'knn_keytype': 'last_ffn_input'}" --knn-keytype last_ffn_input --knn-embed-dim 512 --no-load-keys  --knn-temp 10 --knn-sim-func do_not_recomp_l2 --lmbda 0.8 --use-faiss-only

python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/blob_data/data/CT_vw/wv_ct_data/vw_1m/ende/encoded/bin --gen-subset test --max-tokens 4096 --path /home/ababouelenin/CustomTranslation/knnmt/blob_data/training_dir/checkpoints_deen_pretrained/checkpoint_best.pt --bpe sentencepiece --beam 5 --remove-bpe --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu
# python fairseq_cli/generate.py  /home/ababouelenin/CustomTranslation/knnmt/data-bin/medical.de-en/ --gen-subset valid --path /home/ababouelenin/CustomTranslation/knnmt/checkpoints/wmt19.de-en/model.pt --beam 5 --remove-bpe --bpe fastbpe --bpe-codes /home/ababouelenin/CustomTranslation/knnmt/checkpoints/wmt19.de-en/bpecodes --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu
# python fairseq_cli/generate.py /home/ababouelenin/CustomTranslation/knnmt/data-bin/medical.de-en/ --gen-subset valid --path /home/ababouelenin/CustomTranslation/knnmt/checkpoints/wmt19.de-en/model.pt --beam 5 --remove-bpe --bpe fastbpe --bpe-codes /home/ababouelenin/CustomTranslation/knnmt/checkpoints/wmt19.de-en/bpecodes --tokenizer moses --moses-source-lang de --moses-target-lang en --quiet --sacrebleu --knnmt --k 64 --probe 32 --indexfile /home/ababouelenin/CustomTranslation/knnmt/dstores/medical/index_only.4096.index --model-overrides "{'knn_keytype': 'last_ffn_input'}" --knn-keytype last_ffn_input --knn-embed-dim 1024 --no-load-keys  --knn-temp 10 --knn-sim-func do_not_recomp_l2 --lmbda 0.8 --use-faiss-only
pip install --force-reinstall --no-deps numpy==1.19.5
